//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Aug 10 16:20:25 2017 by ROOT version 6.10/04)
//      from the StreamerInfo in file AOD.root
//////////////////////////////////////////////////////////


#ifndef ElementLink_DataVector_xAOD__CaloCluster_v1____h
#define ElementLink_DataVector_xAOD__CaloCluster_v1____h
namespace xAOD {
class CaloCluster_v1;
} // end of namespace.
template <typename T0> class DataVector;
template <> class DataVector<xAOD::CaloCluster_v1>;
template <typename T0> class ElementLink;
template <> class ElementLink<DataVector<xAOD::CaloCluster_v1> >;

#include "Rtypes.h"
#include "DataVector_xAOD__CaloCluster_v1_.h"
#include "ElementLinkBase.h"

template <typename T0> class ElementLink;
template <> class ElementLink<DataVector<xAOD::CaloCluster_v1> > : public ElementLinkBase {

public:
// Nested classes declaration.

public:
// Data Members.

   /*ElementLink();
   ElementLink(const ElementLink & );
   virtual ~ElementLink();*/

};
#endif
