//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Aug 10 16:20:25 2017 by ROOT version 6.10/04)
//      from the StreamerInfo in file AOD.root
//////////////////////////////////////////////////////////


#ifndef ElementLinkBase_h
#define ElementLinkBase_h
class ElementLinkBase;

#include "Rtypes.h"

class ElementLinkBase {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int m_persKey;    //
   unsigned int m_persIndex;    //

   /*ElementLinkBase();
   ElementLinkBase(const ElementLinkBase & );
   virtual ~ElementLinkBase();*/

};
#endif
