//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Aug 10 16:20:25 2017 by ROOT version 6.10/04)
//      from the StreamerInfo in file AOD.root
//////////////////////////////////////////////////////////


#ifndef ILockable_h
#define ILockable_h
class ILockable;

#include "Rtypes.h"

class ILockable {

public:
// Nested classes declaration.

public:
// Data Members.

   /*ILockable();
   ILockable(const ILockable & );
   virtual ~ILockable();*/

};
#endif
