//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Aug 10 16:20:25 2017 by ROOT version 6.10/04)
//      from the StreamerInfo in file AOD.root
//////////////////////////////////////////////////////////


#ifndef SG__IAuxStore_h
#define SG__IAuxStore_h
namespace SG {
class IAuxStore;
} // end of namespace.

#include "Rtypes.h"
#include "SG__IConstAuxStore.h"

namespace SG {
class IAuxStore : public SG::IConstAuxStore {

public:
// Nested classes declaration.

public:
// Data Members.

   /*IAuxStore();
   IAuxStore(const IAuxStore & );
   virtual ~IAuxStore();*/

};
} // namespace
#endif
