//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Aug 10 16:20:25 2017 by ROOT version 6.10/04)
//      from the StreamerInfo in file AOD.root
//////////////////////////////////////////////////////////


#ifndef SG__IAuxStoreIO_h
#define SG__IAuxStoreIO_h
namespace SG {
class IAuxStoreIO;
} // end of namespace.

#include "Rtypes.h"

namespace SG {
class IAuxStoreIO {

public:
// Nested classes declaration.

public:
// Data Members.

   /*IAuxStoreIO();
   IAuxStoreIO(const IAuxStoreIO & );
   virtual ~IAuxStoreIO();*/

};
} // namespace
#endif
