//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Aug 10 16:20:25 2017 by ROOT version 6.10/04)
//      from the StreamerInfo in file AOD.root
//////////////////////////////////////////////////////////


#ifndef SG__AuxElement_h
#define SG__AuxElement_h
namespace SG {
class AuxElement;
} // end of namespace.

#include "Rtypes.h"
#include "SG__IAuxElement.h"

namespace SG {
class AuxElement : public SG::IAuxElement {

public:
// Nested classes declaration.

public:
// Data Members.

   /*AuxElement();
   AuxElement(const AuxElement & );
   virtual ~AuxElement();*/

};
} // namespace
#endif
