//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Aug 10 16:20:25 2017 by ROOT version 6.10/04)
//      from the StreamerInfo in file AOD.root
//////////////////////////////////////////////////////////


#ifndef SG__IAuxStoreHolder_h
#define SG__IAuxStoreHolder_h
namespace SG {
class IAuxStoreHolder;
} // end of namespace.

#include "Rtypes.h"

namespace SG {
class IAuxStoreHolder {

public:
// Nested classes declaration.

public:
// Data Members.

   /*IAuxStoreHolder();
   IAuxStoreHolder(const IAuxStoreHolder & );
   virtual ~IAuxStoreHolder();*/

};
} // namespace
#endif
