//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Aug 10 16:20:25 2017 by ROOT version 6.10/04)
//      from the StreamerInfo in file AOD.root
//////////////////////////////////////////////////////////


#ifndef SG__IConstAuxStore_h
#define SG__IConstAuxStore_h
namespace SG {
class IConstAuxStore;
} // end of namespace.

#include "Rtypes.h"

namespace SG {
class IConstAuxStore {

public:
// Nested classes declaration.

public:
// Data Members.

   /*IConstAuxStore();
   IConstAuxStore(const IConstAuxStore & );
   virtual ~IConstAuxStore();*/

};
} // namespace
#endif
