//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Aug 10 16:20:25 2017 by ROOT version 6.10/04)
//      from the StreamerInfo in file AOD.root
//////////////////////////////////////////////////////////


#ifndef SG__IAuxElement_h
#define SG__IAuxElement_h
namespace SG {
class IAuxElement;
} // end of namespace.

#include "Rtypes.h"

namespace SG {
class IAuxElement {

public:
// Nested classes declaration.

public:
// Data Members.

   /*IAuxElement();
   IAuxElement(const IAuxElement & );
   virtual ~IAuxElement();*/

};
} // namespace
#endif
