//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Aug 10 16:20:25 2017 by ROOT version 6.10/04)
//      from the StreamerInfo in file AOD.root
//////////////////////////////////////////////////////////


#ifndef xAOD__IParticle_h
#define xAOD__IParticle_h
namespace xAOD {
class IParticle;
} // end of namespace.

#include "Rtypes.h"
#include "SG__AuxElement.h"

namespace xAOD {
class IParticle : public SG::AuxElement {

public:
// Nested classes declaration.

public:
// Data Members.

   IParticle();
   IParticle(const IParticle & );
   virtual ~IParticle();

};
} // namespace
#endif
