//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Aug 10 16:20:25 2017 by ROOT version 6.10/04)
//      from the StreamerInfo in file AOD.root
//////////////////////////////////////////////////////////


#ifndef xAOD__AuxContainerBase_h
#define xAOD__AuxContainerBase_h
namespace xAOD {
class AuxContainerBase;
} // end of namespace.

#include "Rtypes.h"
#include "SG__IAuxStore.h"
#include "SG__IAuxStoreIO.h"
#include "SG__IAuxStoreHolder.h"
#include "ILockable.h"

namespace xAOD {
class AuxContainerBase : public SG::IAuxStore , public SG::IAuxStoreIO , public SG::IAuxStoreHolder , public ILockable {

public:
// Nested classes declaration.

public:
// Data Members.

   /*AuxContainerBase();
   AuxContainerBase(const AuxContainerBase & );
   virtual ~AuxContainerBase();*/

};
} // namespace
#endif
